import test from 'node:test';
import assert from 'node:assert/strict';
import {makeChunkIndex} from '../lib/media/finals/chunk-index.ts';
const uid=n=>`${n}1111111-1111-4111-8111-111111111111`;
const identity={actorId:uid(2),sessionHash:'a'.repeat(64),operator:false,scope:{organizationId:uid(1),bookingId:uid(3),propertyId:uid(4)}};
const env={PHOTO_FINALS_RESUMABLE_ENABLED:'1',PHOTO_FINALS_ENABLED:'true',PHOTO_FINALS_ENVIRONMENT:'synthetic-local',NODE_ENV:'test',PHOTO_FINALS_SYNTHETIC_ACK:'isolated-no-network',PHOTO_FINALS_ALLOWED_SCOPES:JSON.stringify([identity.scope])};
const ix=makeChunkIndex({organization_id:uid(1),package_id:uid(5),release_id:uid(6),manifest_sha256:'b'.repeat(64)},{bytes:5,sha256:'c'.repeat(64),digests:'d'.repeat(64)});
const state={transfer:{id:uid(7),expires_at:new Date(Date.now()+60000).toISOString()},index:ix,package:{id:uid(5),organization_id:uid(1),release_id:uid(6),sha256:'\\x'+'c'.repeat(64),byte_size:5,object_key:`packages/${uid(1)}/${uid(6)}/full_res_zip/${'c'.repeat(64)}.zip`},coverage:[]};
function setup(extra={}){const calls=[];const deps={env,authorize:async()=>identity,runtime:async()=>({env,db:{rpc:async(n,a)=>{calls.push({n,a});return {data:state,error:null};}},storage:{}}),...extra};return {calls,h:mod.createResumeHandler(deps)};}
const post=body=>new Request('http://localhost/resume',{method:'POST',headers:{origin:'http://localhost','content-type':'application/json'},body:JSON.stringify(body)});
test('begin requires current session and returns bounded index DTO without private object keys',async()=>{const f=setup();const r=await f.h(post({op:'begin',packageId:uid(5)}),uid(3));assert.equal(r.status,200);const dto=await r.json();assert.equal(dto.transferId,uid(7));assert.deepEqual(dto.chunkDigests,['d'.repeat(64)]);assert.equal(JSON.stringify(dto).includes('object_key'),false);assert.equal(f.calls[0].n,'photo_finals_transfer_begin');assert.equal(f.calls[0].a.p_session,identity.sessionHash);assert.equal(f.calls[0].a.p_package,uid(5));});
test('progress uses bound session and explicit resume invokes rebind RPC',async()=>{const f=setup();for(const [request,op] of [[new Request(`http://localhost/resume?transferId=${uid(7)}`),'status'],[post({op:'resume',transferId:uid(7)}),'resume']]){const r=await f.h(request,uid(3));assert.equal(r.status,200);assert.equal(f.calls.at(-1).n,'photo_finals_transfer_'+op);assert.equal(f.calls.at(-1).a.p_transfer,uid(7));}});
test('absolute admission includes ignored-signal auth and request abort',async()=>{for(const abort of [false,true]){let signal;const f=setup({authorize:async(_r,_b,s)=>{signal=s;return new Promise(()=>{});}}),c=new AbortController(),r=new Request('http://localhost/resume',{signal:c.signal});const pending=f.h(r,uid(3),Date.now()-9990);if(abort){await new Promise(resolve=>queueMicrotask(resolve));c.abort();}const response=await Promise.race([pending,new Promise((_,reject)=>setTimeout(()=>reject(Error('hang')),100))]);assert.equal(response.status,503);assert.equal(signal.aborted,true);}});
import * as mod from '../lib/media/finals/resume-http.ts';
test('disabled before auth or credential construction',async()=>{assert.equal(typeof mod.createResumeHandler,'function');const h=mod.createResumeHandler({env:{},authorize(){throw Error('auth');},runtime(){throw Error('runtime');}});assert.equal((await h(new Request('http://localhost/resume'),'bad')).status,503);});
